###  **1 El principal motivo de contactos, representa al menos un 30% del volumen total y además este representa mas del 40% del tiempo opertativo insumido**

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
import seaborn

In [3]:
rutaexcel = r"C:\\Users\\Lucia\Desktop\\bootcamp\\Proyecto_EDA_Pablo_Mendez\\Telecom Company Call-Center-Dataset.xlsx"
bbdd = pd.read_excel(rutaexcel)
bbdd

,Call Id,Agent,Date,Time,Topic,Answered (Y/N),Resolved,Speed of answer in seconds,AvgTalkDuration,Satisfaction rating
0,ID0033,Diane,2021-01-01,13:33:36,Technical Support,Y,Y,57.0,00:06:49,3.0
1,ID0056,Dan,2021-01-01,17:44:10,Streaming,Y,Y,83.0,00:06:45,4.0
2,ID0039,Stewart,2021-01-01,14:38:24,Contract related,Y,Y,74.0,00:06:41,1.0
3,ID0009,Greg,2021-01-01,11:13:55,Admin Support,Y,Y,15.0,00:06:38,4.0
4,ID0043,Diane,2021-01-01,14:47:02,Technical Support,Y,Y,45.0,00:06:21,3.0
...,...,...,...,...,...,...,...,...,...,...
4995,ID4992,Joe,2021-03-31,14:13:55,Streaming,N,N,NaN,NaN,NaN
4996,ID4993,Joe,2021-03-31,14:18:14,Admin Support,N,N,NaN,NaN,NaN
4997,ID4994,Greg,2021-03-31,14:58:34,Contract related,N,N,NaN,NaN,NaN
4998,ID4995,Dan,2021-03-31,15:33:07,Payment related,N,N,NaN,NaN,NaN
4999,ID5000,Diane,2021-03-31,17:39:50,Contract related,N,N,NaN,NaN,NaN

In [8]:
basesinnan = bbdd.dropna()

total_call_ids = basesinnan['Call Id'].count()

total_topic = basesinnan.groupby('Topic')['Call Id'].count()
print(total_topic)




porcentaje_por_topic = (total_topic / total_call_ids) * 100 

print(porcentaje_por_topic)

Topic
Admin Support        795
Contract related     789
Payment related      818
Streaming            847
Technical Support    805
Name: Call Id, dtype: int64
Topic
Admin Support        19.610261
Contract related     19.462259
Payment related      20.177602
Streaming            20.892945
Technical Support    19.856931
Name: Call Id, dtype: float64

In [1]:
mayorcontacto = bbdd[bbdd['Topic'] == 'Streaming']

basesinnan = bbdd.dropna()

NameError: name 'bbdd' is not defined

In [ ]:
#primero hay que limpiar la bbdd
#df.groupby('key').aggregate(['min', 'median', 'max'])
#df.groupby('key').aggregate(['min', 'median', 'max', np.mean ,sum])
#df.groupby('key').aggregate({'data1': 'min',
#                             'data2': 'max'})
#usar display para ver varios dt a la vez
# con el astype puedo modificar el date time
#hacer la limpieza y guardar el excel